# vinOS theme: catppuccin-mocha
name = catppuccin-mocha
description = warm dark plum with mauve accents

background = 1e1e2e
foreground = cdd6f4
accent     = cba6f7
border     = cba6f7
muted      = 6c7086
red        = f38ba8
green      = a6e3a1
yellow     = f9e2af
blue       = 89b4fa
magenta    = cba6f7
cyan       = 89dceb

wallpaper  = wallpaper.png
