exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- mako
exec-once = ! vinos-toggle-enabled waybar-off && uwsm-app -- waybar
exec-once = uwsm-app -- fcitx5 --disable notificationitem
exec-once = uwsm-app -- swaybg -i ~/.config/vinos/theme/background -m fill
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = vinos-first-run
exec-once = vinos-powerprofiles-init
exec-once = uwsm-app -- vinos-hyprland-monitor-watch

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all

# Run post-boot hooks after startup config has loaded
exec-once = sleep 2 && vinos-hook post-boot
