#!/usr/bin/env bash
# iso/gen-packages.sh — regenerate iso/profile/packages.x86_64 as the sorted
# union of packages.releng, packages.live, and every argument to install_pkg
# in install/01-base.sh and install/02-desktop.sh. Spec §3.2: never
# hand-edit the output; CI fails if regeneration produces a diff.
#
# install_aur args are extracted into iso/aur.list (consumed by build.sh
# when producing the local vinos-aur repo per §6). Comments (#...) and
# blank lines in the .releng and .live inputs are stripped.
set -euo pipefail

ISO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$ISO_DIR/.." && pwd)"
OUT="$ISO_DIR/profile/packages.x86_64"
AUR_OUT="$ISO_DIR/aur.list"

# Extract every positional argument to install_pkg / install_aur inside the
# base install scripts. `bash -n` would validate syntax; here we just grep.
# Line contract: `install_pkg pkg1 pkg2 \` (backslash-continue allowed).
extract_fn_args() {
  local fn="$1" file
  shift
  for file in "$@"; do
    [[ -f "$file" ]] || continue
    # Join backslash-continued lines, then match `<fn> a b c ...`. Missing
    # matches are non-fatal (a stub script with zero install_pkg lines is
    # legal; grep -c is used instead of pipe-fail to survive no-match).
    awk '/\\$/{sub(/\\$/,""); printf "%s",$0; next}1' "$file" \
      | { grep -E "^[[:space:]]*${fn}([[:space:]]|$)" || true; } \
      | sed -E "s/^[[:space:]]*${fn}[[:space:]]+//; s/#.*$//" \
      | tr -s ' \t' '\n'
  done
}

strip() { grep -Ev '^\s*(#|$)' "$1" 2>/dev/null || true; }

# awk drops blank lines so the sort-u output can be empty (legal, e.g.
# when both 01/02 have zero install_aur calls). LC_ALL=C keeps sort
# deterministic across locales. install_aur args are merged into
# packages.x86_64 too — the local [vinos-aur] pacman repo built by
# aur-build.sh is added to pacman.conf, so mkarchiso pacstraps them
# from there just like any other package.
{
  strip "$ISO_DIR/packages.releng"
  strip "$ISO_DIR/packages.live"
  strip "$ISO_DIR/aur.live"
  extract_fn_args install_pkg "$REPO/install/01-base.sh" "$REPO/install/02-desktop.sh"
  extract_fn_args install_aur "$REPO/install/01-base.sh" "$REPO/install/02-desktop.sh"
} | awk 'NF' | LC_ALL=C sort -u > "${OUT}.tmp"

{
  extract_fn_args install_aur "$REPO/install/01-base.sh" "$REPO/install/02-desktop.sh"
  strip "$ISO_DIR/aur.live"
} | awk 'NF' | LC_ALL=C sort -u > "${AUR_OUT}.tmp"

{
  printf '# GENERATED by iso/gen-packages.sh — do not hand-edit.\n'
  printf '# Sources: iso/packages.releng, iso/packages.live,\n'
  printf '#          install/01-base.sh install_pkg args,\n'
  printf '#          install/02-desktop.sh install_pkg args.\n'
  cat "${OUT}.tmp"
} > "$OUT"

mv "${AUR_OUT}.tmp" "$AUR_OUT"
rm -f "${OUT}.tmp"

printf 'wrote %s (%d packages)\n' "$OUT" "$(wc -l < "$OUT")"
printf 'wrote %s (%d AUR packages)\n' "$AUR_OUT" "$(wc -l < "$AUR_OUT")"
