# vinOS theme: rose-pine
name = rose-pine
description = dusky rose on deep midnight

background = 191724
foreground = e0def4
accent     = ebbcba
border     = ebbcba
muted      = 6e6a86
red        = eb6f92
green      = 9ccfd8
yellow     = f6c177
blue       = 31748f
magenta    = c4a7e7
cyan       = 9ccfd8

wallpaper  = wallpaper.png
