#!/usr/bin/env bash
# gen-theme-data.sh — read every configs/vinos/brand/themes/*/colors.toml
# and emit site/static/js/theme-data.js as `window.VINOS_THEMES = {...}`.
#
# Run this whenever a palette changes. It's cheap and idempotent.
#
# Output shape (per theme):
#   { mode, accent, selection, muted,
#     bg, bgDark, bgDarker, bgLight,
#     fg, fgDark, fgLight, fgBright,
#     red, yellow, orange, green, cyan, blue, magenta, brown }

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
THEMES_DIR="$ROOT/configs/vinos/brand/themes"
OUT="$ROOT/site/static/js/theme-data.js"

mkdir -p "$(dirname "$OUT")"

# The theme order we ship (mirrors the chip strip order).
ORDER=(cosmos circuit egret reef crater dusk prism bloom summit ridge)

get() {
  # get <file> <key>  → prints the quoted value from a TOML line like  key = "#..."
  local f="$1" k="$2"
  awk -v k="$k" '
    $0 ~ "^"k"[ \t]*=" {
      match($0, /"[^"]*"/)
      if (RSTART) print substr($0, RSTART+1, RLENGTH-2)
      exit
    }
  ' "$f"
}

{
  echo "// AUTO-GENERATED by site/tools/gen-theme-data.sh"
  echo "// Source: configs/vinos/brand/themes/*/colors.toml"
  echo "// Do not hand-edit. Re-run the script when palettes change."
  echo "window.VINOS_THEMES = {"

  for slug in "${ORDER[@]}"; do
    f="$THEMES_DIR/$slug/colors.toml"
    [[ -f "$f" ]] || { echo "  // MISSING: $slug" ; continue ; }

    mode=$(get "$f" mode)
    accent=$(get "$f" accent)
    selection=$(get "$f" selection)
    muted=$(get "$f" muted)
    bg=$(get "$f" background)
    bgDark=$(get "$f" dark_background)
    bgDarker=$(get "$f" darker_background)
    bgLight=$(get "$f" lighter_background)
    fg=$(get "$f" foreground)
    fgDark=$(get "$f" dark_foreground)
    fgLight=$(get "$f" light_foreground)
    fgBright=$(get "$f" bright_foreground)
    red=$(get "$f" red)
    yellow=$(get "$f" yellow)
    orange=$(get "$f" orange)
    green=$(get "$f" green)
    cyan=$(get "$f" cyan)
    blue=$(get "$f" blue)
    magenta=$(get "$f" magenta)
    brown=$(get "$f" brown)

    cat <<EOF
  $slug: {
    mode: "$mode",
    accent: "$accent", selection: "$selection", muted: "$muted",
    bg: "$bg", bgDark: "$bgDark", bgDarker: "$bgDarker", bgLight: "$bgLight",
    fg: "$fg", fgDark: "$fgDark", fgLight: "$fgLight", fgBright: "$fgBright",
    red: "$red", yellow: "$yellow", orange: "$orange", green: "$green",
    cyan: "$cyan", blue: "$blue", magenta: "$magenta", brown: "$brown"
  },
EOF
  done

  echo "};"
  echo "window.VINOS_THEME_ORDER = [\"${ORDER[*]// /\", \"}\"];"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
