#!/usr/bin/env bash
# 03-configs.sh — deploy vinOS desktop configs into target filesystem.
# Clean-room; no Omarchy code, no /usr/share/omarchy paths.
#
# Source-of-truth layout (all under repo's configs/vinos/):
#   configs/vinos/hypr/*.conf              → /etc/skel/.config/hypr/
#   configs/vinos/default/hypr/            → /usr/share/vinos/default/hypr/
#   configs/vinos/default/waybar/          → /etc/skel/.config/waybar/
#   configs/vinos/default/mako/config      → /etc/skel/.config/mako/config
#   configs/vinos/default/walker/          → /etc/skel/.config/walker/
#   configs/vinos/default/foot/foot.ini    → /etc/skel/.config/foot/foot.ini
#   configs/vinos/default/vinos/vinos-menu.jsonc → /usr/share/vinos/default/vinos/vinos-menu.jsonc
#   configs/vinos/brand/themes/<name>/     → /usr/share/vinos/themes/<name>/
#
# Everything else installed via 05-branding.sh (bins), 02-desktop.sh
# (packages + service enable), 04-services.sh (network + firewall).

set -euo pipefail
# shellcheck source=../lib/common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

VINOS_SRC="$REPO/configs/vinos"
[[ -d "$VINOS_SRC" ]] || { log "03-configs: $VINOS_SRC missing — nothing to deploy"; exit 0; }

# Helper: rsync a subtree into target root under $prefix (honors VINOS_ROOT).
_deploy() {
  local src="$1" prefix="$2"
  [[ -e "$src" ]] || return 0
  local dest; dest="$(_rootpath "$prefix")"
  _sudo install -d -m 0755 "$(dirname "$dest")"
  log "03-configs: deploying $(basename "$src") → $prefix"
  if [[ -d "$src" ]]; then
    _sudo install -d -m 0755 "$dest"
    _sudo rsync -a --exclude='.git' "$src/" "$dest/"
  else
    _sudo install -Dm 0644 "$src" "$dest"
  fi
}

# ── User-facing skel configs ───────────────────────────────────────
_deploy "$VINOS_SRC/hypr"                       /etc/skel/.config/hypr
_deploy "$VINOS_SRC/default/waybar"             /etc/skel/.config/waybar
_deploy "$VINOS_SRC/default/mako/config"        /etc/skel/.config/mako/config
_deploy "$VINOS_SRC/default/walker"             /etc/skel/.config/walker
_deploy "$VINOS_SRC/default/foot/foot.ini"      /etc/skel/.config/foot/foot.ini

# ── System-wide defaults (sourced by user configs) ────────────────
_deploy "$VINOS_SRC/default/hypr"               /usr/share/vinos/default/hypr
_deploy "$VINOS_SRC/default/vinos"              /usr/share/vinos/default/vinos

# ── vinOS themes → /usr/share/vinos/themes/ ────────────────────────
if [[ -d "$VINOS_SRC/brand/themes" ]]; then
  dest="$(_rootpath /usr/share/vinos/themes)"
  _sudo install -d -m 0755 "$dest"
  log "03-configs: installing vinOS themes → /usr/share/vinos/themes"
  for _t in "$VINOS_SRC/brand/themes"/*/; do
    [[ -d "$_t" ]] || continue
    _tname="$(basename "$_t" | tr 'A-Z' 'a-z')"
    _sudo rsync -a --exclude='.git' --exclude='build-themes.sh' "$_t" "$dest/$_tname/"
    log "  + $_tname"
  done
  unset _t _tname dest
fi

# ── Per-theme foot.ini from colors.toml (foot.include= source) ────
_themes_dst="$(_rootpath /usr/share/vinos/themes)"
if [[ -d "$_themes_dst" ]]; then
  log "03-configs: generating foot.ini per theme (from colors.toml)"
  _generated=0
  for _tdir in "$_themes_dst"/*/; do
    _tdir="${_tdir%/}"
    _colors="$_tdir/colors.toml"
    [[ -f "$_colors" ]] || continue
    _get() {
      local val
      val=$(grep -E "^$1[[:space:]]*=" "$_colors" 2>/dev/null \
              | head -1 \
              | sed -nE 's/.*"#?([A-Fa-f0-9]{6})".*/\1/p' \
              | tr 'A-F' 'a-f')
      printf '%s' "${val:-${2:-}}"
    }
    _fg=$(_get foreground);           _bg=$(_get background)
    _dbg=$(_get dark_background "$_bg")
    _lfg=$(_get light_foreground "$_fg")
    _r=$(_get red);    _g=$(_get green);   _y=$(_get yellow); _b=$(_get blue)
    _m=$(_get magenta); _c=$(_get cyan)
    _br=$(_get bright_red "$_r");      _bg2=$(_get bright_green "$_g")
    _by=$(_get bright_yellow "$_y");   _bb=$(_get bright_blue "$_b")
    _bm=$(_get bright_magenta "$_m");  _bc=$(_get bright_cyan "$_c")
    [[ -n "$_fg" && -n "$_bg" ]] || continue
    _foot_tmp="$(mktemp)"
    cat > "$_foot_tmp" <<FOOT
# Generated by vinOS install/03-configs.sh from colors.toml
[colors-dark]
foreground=$_fg
background=$_bg
regular0=$_dbg
regular1=$_r
regular2=$_g
regular3=$_y
regular4=$_b
regular5=$_m
regular6=$_c
regular7=$_lfg
bright0=$_dbg
bright1=$_br
bright2=$_bg2
bright3=$_by
bright4=$_bb
bright5=$_bm
bright6=$_bc
bright7=$_fg
FOOT
    _sudo install -Dm 0644 "$_foot_tmp" "$_tdir/foot.ini"
    rm -f "$_foot_tmp"
    _generated=$((_generated + 1))
  done
  log "03-configs: wrote foot.ini for $_generated themes"
  unset _tdir _colors _fg _bg _r _g _y _b _m _c _br _bg2 _by _bb _bm _bc _dbg _lfg _foot_tmp _generated
fi

# ── Default theme: cosmos (Milky Way over alpine lake) ────────────
_active_theme="${VINOS_THEME:-cosmos}"
_active_theme="$(printf '%s' "$_active_theme" | tr 'A-Z' 'a-z')"

# Seed the skel state dir so a first-boot user has the theme active
_state_skel="$(_rootpath /etc/skel/.local/state/vinos/current)"
_sudo install -d -m 0755 "$_state_skel"
if [[ -d "$(_rootpath /usr/share/vinos/themes/${_active_theme})" ]]; then
  _sudo ln -sfn "/usr/share/vinos/themes/${_active_theme}" "$_state_skel/theme"
  # Wallpaper: seed /etc/skel/.config/vinos/wallpaper.png as a symlink into theme
  _wallpaper_skel="$(_rootpath /etc/skel/.config/vinos)"
  _sudo install -d -m 0755 "$_wallpaper_skel"
  _sudo ln -sfn "/usr/share/vinos/themes/${_active_theme}/wallpaper.png" "$_wallpaper_skel/wallpaper.png"
  log "03-configs: default theme = $_active_theme (cosmos wallpaper)"
fi
unset _active_theme _state_skel _wallpaper_skel

log "03-configs: done"
