title    ➜  vinOS — Apple T2 Mac + persistence  (needs flash.sh --with-persistence)
sort-key 00-a
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-t2
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-t2.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_device=/dev/disk/by-label/vinos-persist quiet splash loglevel=3 vt.global_cursor_default=0 modprobe.blacklist=floppy intel_iommu=on iommu=pt cfg80211.ieee80211_regdom=US console=tty0 console=ttyS0,115200
