title    ➜  vinOS — Apple T2 Mac  (2018-2020 MBP/MBA/iMac Pro)
sort-key 00
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-t2
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-t2.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% quiet splash loglevel=3 vt.global_cursor_default=0 modprobe.blacklist=floppy intel_iommu=on iommu=pt pcie_ports=compat cfg80211.ieee80211_regdom=US console=tty0 console=ttyS0,115200
