title    ⚡  Install vinOS to disk  (Apple T2 Mac — guided)
sort-key 0-install-a
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-t2
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-t2.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% vinos.action=install quiet splash loglevel=3 modprobe.blacklist=floppy intel_iommu=on iommu=pt cfg80211.ieee80211_regdom=US console=tty0 console=ttyS0,115200
