title    ➜  Boot vinOS  —  Intel / AMD / generic PC
sort-key 03
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% quiet splash loglevel=3 vt.global_cursor_default=0 modprobe.blacklist=floppy console=tty0 console=ttyS0,115200
